### ISSUE TITLE
Actualizar Django + docker

### ISSUE THREAD

**Issue by tinchou** [maru/fiubar#1]
Hola!

Estaba intentando armar el Dockerfile para correr y deployar la app de forma fácil. Con solo hacer "docker build ." descargaría todas las dependencias, pero resulta que la versión de Django 1.2 es muy vieja, y pasan dos cosas:
- Django no provee imágenes de docker anteriores a 1.7
- Hay cosas incompatibles con la versión actual desde 1.2, y no lo pude hacer andar

Acá está lo que hice https://github.com/tinchou/fiubar/commit/d09e689fa8cfaff9a43c3eec170e360d96614657

Si en algún momento vuelvo a tener tiempo lo investigo, pero si querés mirarlo vos también sería genial. Si no lo conocés, te prometo que Docker es magia y va a cambiar tu vida jaja.

Saludos!

**Comment by maru** [comment]
Hola! Efectivamente hay varias incompatibilidades con la versión actual de Django, y justamente estaba actualizando el código de Fiubar.

Espero poder terminar en estos días!

Gracias por el dato de Docker! Lo usé pero nunca intenté armar un Dockerfile. Es una buena idea usarlo para este proyecto!

Saludos y te tengo al tanto!

**Comment by tinchou** [comment]
Yo lo hago más que nada porque estoy en Windows porque no existen drivers para mi placa de wifi. Con Docker puedo levantar estos proyectos para Linux con `docker run` y corren re bien jaja.

**Comment by maru** [comment]
Woohoo! Casi 3 años después, pero lo hice! 

No sólo ahora se puede correr en docker, sino que también aprendí sobre virtual environments de python :astonished: 

Seguro que ya te recibiste, te casaste, tenés hijos y te jubilaste, peeeero... bueno, quería contestarte :sweat_smile: 

Saludos!

**Comment by tinchou** [comment]
Alto laburo, felicitaciones :). Yo aún no me recibí pero me cambié a Exactas, así que si querés extender la compatibilidad quizás aún lo pueda usar jaja.
