### ISSUE TITLE
pip requirements

### ISSUE THREAD

**Issue by tinchou** [maru/fiubar#2]
Ah, me olvidaba. Para correr la app hacen falta dependencias como Python Imaging Library. También, al actualizar Django, hay que incluir librerías con cosas que están deprecated.

Agregué las cosas que vi que se iban necesitando para hacerlo andar, pero seguro faltan cosas. Acá está el `requirements.txt`: https://github.com/tinchou/fiubar/blob/master/fiubar/requirements.txt (quizás podría moverse al root). Creo que con `pip freeze` en la máquina que tenés corriendo el server, podés generar el archivo requirements automáticamente.

Después con `pip install -r requirements.txt` levanta todo lo que necesita automáticamente.

**Comment by maru** [comment]
:+1: Hecho en #3
